adafruit:
  key: ''
  username: ''

log:
  file_name: 'logs/log'
  print_format: '%(asctime)s - %(levelname)s - %(message)s'
  level: 'WARNING'  # INFO WARNING ERROR
  
leds:
  night_off: True
  night_start_hour: 23  # 23:00
  night_end_hour: 7  # 07:00
